### ISSUE TITLE
request: incorporate code into lib

### ISSUE THREAD

**Issue by jinjirosan** [karlbunch/pytrack-poller#1]
Hi Karl,
Awesome job on the code, this was exactly what I'm looking for! 
I've looked into using the pytrack default L76GNSS.py (too limited currently) or MicropyGPS code (too much/large).

I'm learning (micro)Python as I go which is going ok but I'm not nearly on your skill level. Hopefully you can help me out.

I'm thinking of trimming your main.py as I don't need all the NMEA sentences. Use it as a lib (e.g. pytrack-poller.py) by placing it as a frozen module in the firmware (as the SiPy has limited memory). And then call the lib from my main.py to get the values into vars.

I'd need the following in vars in the main.py:
- GPS time
- LAT
- LON
- Fix quality
- number of satellites
- Last fix
- Battery

What would be your best way of fetching just these values from pytrack-poller.py into main.py ?

Thx again for putting this stuff out there!
Jin

**Comment by karlbunch** [comment]
I'll try and refactor it a bit to be easier to use as a lib.  Might not be right away as I'm a bit busy right now.  I'll start pushing small commits to move that direction.  First will be clearer separation between the poller and logger so you could easily provide your own logger to be called on a regular basis.

What sentences do you want to parse the "fix quality" from?  And the number of satellites you mean just the raw count of ones used for the fix?

**Comment by jinjirosan** [comment]
Thx for your reply and willingness to help me (figure) this out. I'm also not in a hurry, just trying to get there and learn more.

The fix quality is from GPGGA, the options are 0 (invalid) - 1 (GPS fix) - 2 (DGPS fix). 

Yes, the number of sats is the number used for the fix. It would be nice if it could be updated during the GPS fix process. Sometimes obtaining a fix takes a long time and knowing how many satellites are in view helps.

From your previous release I've taken the GPS_poller and GPS_logger and placed those functions in a separate library. I used the following in main.py to get the values there:
```
GPSoutput = (poller.__dict__)
locals().update(state)  # put the content of STATE into vars
```
But I'm running into difficulties getting data as mentioned into vars. "Have_fix" is no problem but the latitude and longitude I'm struggling a bit. Can't seem to fetch the keys that start with a dollar sign.

This is my project, code and goal:
https://github.com/jinjirosan/PycomTRACKER

**Comment by karlbunch** [comment]
I would suggest looking at today’s latest commit where I broke out the logger class more.. You should be able to easily write a gos logger class to pass in and have updates com through the log_state() function in your class...

**Comment by jinjirosan** [comment]
Thx, I'll have look.

**Comment by jinjirosan** [comment]
The poller is started from main.py and I can see it trying to obtain a fix. When it gets a fix (have_fix == true) then it crashes.
I start off by setting the initial state in main.py
`have_fix = (False)`
Then (part of) the code runs fine until GPS fix.
```
while(True):
    # time-counter configurations
    final_timer = time.time()
    diff = final_timer - init_timer

    if have_fix == (False): 
        print("Getting Location...")
        poller.run()
        continue
    GPSoutput = (poller.__dict__)
    locals().update(state)  # put the content of STATE into vars
```

It crashes:

```
{"state": {"$GPGGA": "$GPGGA,054833.306,,,,,0,0,,,M,,M,,*44", "$GLGSV-1": "$GLGSV,1,1,02,79,,,35,71,,,34*6E", "errcnt_chkerr": 1, "$GPRMC-V": "$GPRMC,054833.306,V,,,,,1.45,139.47,170418,,,N*42", "$PQPREC": "$PQPREC,W,6,6,3,1*7C", "$PMTK514": "$PMTK514,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0*33", "$GPGLL-V": "$GPGLL,,,,,054833.306,V,N*76", "last_gps_time_zda": "@11241: GPS Time zda: (2018, 4, 17, 5, 48, 33.306) RTC: (2018, 4, 17, 5, 48, 33)", "errcnt_gps_time_zda": 482, "have_fix": false, "$GNZDA": "$GNZDA,054833.306,17,04,2018,,*4D", "last_chkerr": "@2: Skipping invalid msg_chksum(5c) != pkt_chksum(1e): [,A,1,,,,,,,,,,,,,,,*1E]", "$PQTXT": "$PQTXT,W,1,1*22", "$PMTK001": "$PMTK001,313,3*31", "max_buf_len": 254, "max_pkt_len": 51, "$PQVEL": "$PQVEL,-0.546939,0.432797,-0.243577*64", "count_large_buf": 738, "$GPGSV-1": "$GPGSV,2,1,05,05,,,34,13,,,19,16,,,29,07,,,16*7B", "$PMTK010": "$PMTK010,001*2E", "$PMTK011": "$PMTK011,MTKGPS*08", "last_read_bytes": 39, "last_large_buf": 11242, "$GPGSA": "$GPGSA,A,1,,,,,,,,,,,,,,,*1E", "$PQRLM": "$PQRLM,W,1,1*29", "clock_drift": 0, "$GPGSV-2": "$GPGSV,2,2,05,02,,,25*79", "$GPVTG": "$GPVTG,139.47,T,,M,1.45,N,2.69,K,N*37"}, "count": 11267, "battery": 4.686702, "battery_status": "OK", "time": "2018-04-17 05:48:34 UTC", "mem_free": 38384}
Traceback (most recent call last):
  File "main.py", line 45, in <module>
  File "trackerlogger.py", line 97, in run
  File "trackerlogger.py", line 526, in log_stop
  File "trackerlogger.py", line 40, in __str__
  File "trackerlogger.py", line 49, in sorted_dict_str
  File "trackerlogger.py", line 51, in sorted_dict_str
MemoryError: memory allocation failed, allocating 1157 bytes
```
I renamed your library to trackerlogger.py as it will eventually track more than GPS only. "main.py line 45" is poller.run().

But when I manually look into poller.__dict__ in main.py all the info I need is there. I can't see a reason why it would crash.

```
>>> GPSoutput = (poller.__dict__)
>>> 
>>> GPSoutput
{'state': {'$PMTK001': '$PMTK001,313,3*31', '$PQVEL': '$PQVEL,-0.120492,0.085715,0.043007*43', '$PQTXT': '$PQTXT,W,1,1*22', 'clock_drift': 0, 'last_last_fix': '@11479: (52.08066, 4.335925) @ (5, 48, 43.0)', 'last_read_bytes': 38, 'errcnt_chkerr': 1, '$GLGSV-1': '$GLGSV,3,1,09,71,64,321,31,80,60,069,,70,56,106,,73,43,171,*6E', 'errcnt_last_fix': 6, '$GPVTG': '$GPVTG,111.03,T,,M,1.19,N,2.20,K,A*36', 'errcnt_gps_time_zda': 492, '$PQPREC': '$PQPREC,W,6,6,3,1*7C', '$GLGSV-2': '$GLGSV,3,2,09,87,21,314,,88,11,000,29,79,08,025,35,86,08,259,*63', '$GLGSV-3': '$GLGSV,3,3,09,69,02,118,*59', '$GPGSV-1': '$GPGSV,2,1,08,30,67,167,,07,66,085,18,05,59,287,35,37,28,158,*73', '$GPGSV-2': '$GPGSV,2,2,08,02,26,233,27,13,22,265,20,16,06,019,29,06,06,197,*7C', 'fix_start': '(52.08066, 4.335943) @ (5, 48, 40.306)', 'count_large_buf': 761, '$GPGSA': '$GPGSA,A,1,,,,,,,,,,,,,,,*1E', '$PMTK514': '$PMTK514,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0*33', 'last_gps_time_rmc': '@11477: GPS Time rmc: (2018, 4, 17, 5, 48, 43.0) RTC: (2018, 4, 17, 5, 48, 43)', 'last_chkerr': '@2: Skipping invalid msg_chksum(5c) != pkt_chksum(1e): [,A,1,,,,,,,,,,,,,,,*1E]', '$GPGLL-V': '$GPGLL,,,,,054839.306,V,N*7C', 'last_gps_time_zda': '@11477: GPS Time zda: (2018, 4, 17, 5, 48, 43.0) RTC: (2018, 4, 17, 5, 48, 43)', '$GNGSA': '$GNGSA,A,3,79,88,71,,,,,,,,,,3.83,3.73,0.87*14', 'have_fix': True, 'last_large_buf': 11479, 'errcnt_gps_time_rmc': 3, '$PMTK010': '$PMTK010,001*2E', '$PMTK011': '$PMTK011,MTKGPS*08', '$GPGGA': '$GPGGA,054843.000,5204.8394,N,00420.1555,E,1,6,3.73,30.5,M,47.1,M,,*60', 'max_buf_len': 254, '$PQRLM': '$PQRLM,W,1,1*29', '$GNZDA': '$GNZDA,054843.000,17,04,2018,,*4F', 'max_pkt_len': 70, '$GPRMC-V': '$GPRMC,054839.306,V,,,,,1.48,142.32,170418,,,N*4B', '$GNRMC-A': '$GNRMC,054843.000,A,5204.8394,N,00420.1555,E,1.19,111.03,170418,,,A*79', '$GNGLL-A': '$GNGLL,5204.8394,N,00420.1555,E,054843.000,A,A*4E'}, 'cmd_timeout': None, 'time_mode': 'GPS_SEARCH', 'init_cmds': None, 'gps_log': <GPS_SD_Logger object at 3ffe9d00>, 'i2c': I2C(0, I2C.MASTER, baudrate=100000), 'cmd_wait_for': None, 'cmd_queue': [], 'read_count': 11497, 'next_log_time': 1523944134}
>>> 
```

Would you be able to tell what I'm doing wrong?
If you have time, could you provide example code of reading a value from the poller into main.py (e.g. number of sats or (LAT,LON) ?

**Comment by karlbunch** [comment]
I’m offsite all week so won’t have time but to be clear you should write a
function to emulate the GPS_Logger class and pass it to the poller class..
